// <auto-generated />
namespace LeThiHuyen995_DATN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeAdv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeAdv));
        
        string IMigrationMetadata.Id
        {
            get { return "202405140421339_changeAdv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
